apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperproxy
spec:
  template:
    spec:
      containers:
        - name: hyperproxy
          resources:
            limits:
              memory: "1Gi"
