apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: concrnt-valdra

helmCharts:
  - repo: https://charts.concrnt.net/
    name: concrnt
    version: 0.4.4
    releaseName: concrnt
    valuesFile: ./values.yaml

generators:
  - ./configmap-generator.yaml

patchesStrategicMerge:
  - configmap-patch.yaml

patches:
  - path: deployment-patch.yaml
